### ISSUE TITLE
I try to use pip install but can not install

### ISSUE THREAD

**Issue by liubailong-IFS** [khayratk/pypnm#5]
I want use your model to simulate two phase flow in porous media and take capillary force into account, but 

PS: can I add your Line or some other contacts. 
Want to learn some details about your code

**Comment by khayratk** [comment]
The package cannot be installed with pip yet. 
Can you give more details of the problem you are trying to simulate. I can try add an example for you.

**Comment by liubailong-IFS** [comment]
Thanks for your replying, khayratk. I want to do research on the two phase flow in the pore media like rock and to learn the pressure field when injection rate is constant. There is a picture that shows what I want to do. I try to run the pypnm without pip install. In fact, it can not be run. Sorry to troubling you.
My Line is "liubailong".
![image](https://user-images.githubusercontent.com/33473208/37857734-08db62dc-2f41-11e8-8083-e515c8c79b55.png)
